[package]
name = "kaisui-xtra"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
xtra = { version = "0.6.0", features = ["tokio", "wasm_bindgen", "macros"] }
